// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Restituisce le informazioni dell'utente autenticato. Richiede un cookie access_token valido.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "responses": {
                    "200": {
                        "description": "Informazioni utente",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Non autenticato o token scaduto",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/passkeys": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns all passkeys registered by the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passkeys"
                ],
                "summary": "List User Passkeys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.PasskeyResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/passkeys/{id}": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes a passkey. Users can only delete their own passkeys and must keep at least one active.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passkeys"
                ],
                "summary": "Delete Passkey",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Passkey ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Cannot delete last passkey",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not authorized to delete this passkey",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Passkey not found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the name of a passkey. Users can only rename their own passkeys.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "passkeys"
                ],
                "summary": "Rename Passkey",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Passkey ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New Name",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RenamePasskeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid data",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not authorized to modify this passkey",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Passkey not found",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login/begin": {
            "post": {
                "description": "Initiates the WebAuthn authentication flow. Returns options to be passed to navigator.credentials.get() in the browser.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start Passkey Login",
                "parameters": [
                    {
                        "description": "User Email",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PublicKeyCredentialRequestOptions for WebAuthn",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid email",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login/finish": {
            "post": {
                "description": "Completes the WebAuthn authentication flow. If login is successful, sets two HttpOnly cookies: access_token (15 min) and refresh_token (7 days).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Complete Passkey Login",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user@example.com",
                        "description": "User Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "WebAuthn response from navigator.credentials.get()",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login completed, JWT cookies set",
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginSuccessResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "refresh_token=\u003cJWT\u003e; Path=/auth; HttpOnly; SameSite=Lax"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing email",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Token generation error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Clears authentication cookies (access_token and refresh_token).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Logout",
                "responses": {
                    "200": {
                        "description": "Logout completed",
                        "schema": {
                            "$ref": "#/definitions/dtos.MessageResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "refresh_token=; Path=/auth; Max-Age=0; HttpOnly"
                            }
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Uses the refresh token to obtain a new access token. The refresh token is rotated for security.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Renew Access Token",
                "responses": {
                    "200": {
                        "description": "Token renewed",
                        "schema": {
                            "$ref": "#/definitions/dtos.MessageResponse"
                        },
                        "headers": {
                            "Set-Cookie": {
                                "type": "string",
                                "description": "refresh_token=\u003cJWT\u003e; Path=/auth; HttpOnly; SameSite=Lax"
                            }
                        }
                    },
                    "401": {
                        "description": "Missing, invalid, or expired refresh token",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/begin": {
            "post": {
                "description": "Initiates the WebAuthn registration flow. Returns options to be passed to navigator.credentials.create() in the browser.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Start Passkey Registration",
                "parameters": [
                    {
                        "description": "User Email",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PublicKeyCredentialCreationOptions for WebAuthn",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid or missing email",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/finish": {
            "post": {
                "description": "Completes the WebAuthn registration flow. The body must contain the raw response from navigator.credentials.create().",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Complete Passkey Registration",
                "parameters": [
                    {
                        "type": "string",
                        "example": "user@example.com",
                        "description": "User Email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "WebAuthn response from navigator.credentials.create()",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registration completed",
                        "schema": {
                            "$ref": "#/definitions/dtos.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Missing email",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Registration failed",
                        "schema": {
                            "$ref": "#/definitions/dtos.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register/verify-otp": {
            "post": {
                "description": "Verifies the OTP sent to email and returns registration options.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify OTP and Continue Registration",
                "parameters": [
                    {
                        "description": "Email and OTP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PublicKeyCredentialCreationOptions",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Checks the status of the service, database, and Redis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Detailed Health Check",
                "responses": {
                    "200": {
                        "description": "All services are healthy",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthDetailedResponse"
                        }
                    },
                    "503": {
                        "description": "One or more services are unhealthy",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthDetailedResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtos.EmailRequest": {
            "description": "Request body with user email",
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "description": "User's email address\nrequired: true\nexample: user@example.com",
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "dtos.ErrorResponse": {
            "description": "Error details",
            "type": "object",
            "properties": {
                "code": {
                    "description": "Optional error code (e.g., TOKEN_EXPIRED)",
                    "type": "string",
                    "example": "TOKEN_EXPIRED"
                },
                "error": {
                    "description": "Error message\nexample: Invalid request format",
                    "type": "string",
                    "example": "Invalid request format"
                }
            }
        },
        "dtos.LoginSuccessResponse": {
            "description": "Response after successful authentication",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Success message\nexample: Login successful! 🔐",
                    "type": "string",
                    "example": "Login successful! 🔐"
                },
                "user": {
                    "description": "User information",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.UserInfo"
                        }
                    ]
                }
            }
        },
        "dtos.MessageResponse": {
            "description": "Generic response message",
            "type": "object",
            "properties": {
                "message": {
                    "description": "Response message\nexample: Operation successful",
                    "type": "string",
                    "example": "Operation successful"
                }
            }
        },
        "dtos.UserInfo": {
            "description": "Authenticated user details",
            "type": "object",
            "properties": {
                "email": {
                    "description": "User email\nexample: user@example.com",
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "description": "Unique user ID\nexample: 1",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "dtos.UserResponse": {
            "description": "Response containing user info",
            "type": "object",
            "properties": {
                "user": {
                    "description": "Authenticated user info",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.UserInfo"
                        }
                    ]
                }
            }
        },
        "handlers.HealthDetailedResponse": {
            "type": "object",
            "properties": {
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/handlers.ServiceStatus"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "timestamp": {
                    "type": "string"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "handlers.PasskeyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "last_used": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "MacBook Pro"
                }
            }
        },
        "handlers.RenamePasskeyRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "iPhone 15 Pro"
                }
            }
        },
        "handlers.ServiceStatus": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "latency": {
                    "type": "string",
                    "example": "1.23ms"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "description": "JWT token in HttpOnly cookie (set automatically on login)",
            "type": "apiKey",
            "name": "access_token",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go Auth Core API",
	Description:      "WebAuthn/Passkey Authentication API with HttpOnly JWT cookies",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
