package domain

import "gorm.io/gorm"

// Passkey represents a WebAuthn credential stored in the database.
type Passkey struct {
	gorm.Model

	// UserID is the foreign Key linking this passkey to a specific user.
	UserID uint `Gorm:"not null;index"`

	// Name maps to a human-readable device name (e.g., "Mario's MacBook Pro").
	Name string `Gorm:"size:255;not null"`

	// --- WebAuthn Technical Data ---

	// CredentialID is the unique identifier for the credential (generated by the authenticator).
	// Stored as a byte slice.
	CredentialID []byte `Gorm:"uniqueIndex;not null"`

	// PublicKey is the cryptographic public key used for signature verification.
	PublicKey []byte `Gorm:"not null"`

	// SignCount acts as a counter to prevent replay attacks (cloned keys).
	SignCount uint32 `Gorm:"not null;default:0"`

	// Transports indicates the supported transport methods (USB, NFC, BLE, Internal).
	Transports string `Gorm:"size:255"`

	// --- WebAuthn Flags ---

	// BackupEligible indicates if the credential can be backed up (e.g., to iCloud/Google Cloud).
	BackupEligible bool `Gorm:"not null;default:false"`

	// BackupState indicates if the credential is currently backed up.
	BackupState bool `Gorm:"not null;default:false"`
}

// TableName overrides the default table name to "passkeys".
func (Passkey) TableName() string {
	return "passkeys"
}
